#!/bin/sh

mkdir -p public/image/small
neato -n -opublic/image/$1.svg -Tsvg "$2"
sed -i -e 's/<svg.*/<svg width="100%" height="100%"/' public/image/$1.svg
rsvg-convert -a -h 400 -o public/image/$1.png public/image/$1.svg
rsvg-convert -a -h 25 -o public/image/small/$1.png public/image/$1.svg
